version: '3.8'

services:
  backend:
    build: .
    image: locallens-backend
    container_name: locallens-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./app:/srv/app
    restart: unless-stopped
