// Shared TypeScript interfaces used by the minimal UI
// These are lightweight copies of the core interfaces used elsewhere in the project.

export interface TaskRequest {
  // The free‑form prompt entered by the user
  prompt: string;
  // Optional session identifier (generated by the backend if omitted)
  sessionId?: string;
}

export interface StructuredAction {
  // Action type, e.g., "click", "type", "scroll", "wait", "done"
  type: string;
  // Arguments specific to the action type (e.g., elementId, text, x/y offsets)
  args: Record<string, any>;
}

export interface UIElement {
  id: string;
  // Bounding box in page coordinates (optional for overlay)
  bbox?: { x: number; y: number; width: number; height: number };
}

export interface UIGraph {
  // List of UI elements detected on the page
  elements: UIElement[];
  // Optional metadata (e.g., screenshot hash)
  meta?: Record<string, any>;
}
